feat: show custom layer names in style-panel for redability
webstudio-is/webstudio pull request #3633
Opened 2024-06-27 16:12 UTC by JayaKrishnaNamburu

## Description

fixes #3589 

This PR allows to display the layers in the style-panel in much more readable way.  

![Screenshot 2024-06-27 at 9 40 14 PM](https://github.com/webstudio-is/webstudio/assets/11075561/cfec0958-b228-476a-992b-d38b762892c6)
![Screenshot 2024-06-27 at 9 40 34 PM](https://github.com/webstudio-is/webstudio/assets/11075561/c6615957-d073-437f-b8b2-56ee191b672d)

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [x] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [x] tested locally and on preview environment (preview dev login: 5de6)

2024-06-28 11:36 UTC, kof commented
Drop Shadow vs Outer shadow notation is inconsistent

2024-06-28 11:40 UTC, kof commented on apps/builder/app/builder/features/style-panel/style-layer-utils.ts
> +export const extractNameAndValueFromLayer = (
I would call this function something more like: getHumanizedTextFromLayer

2024-06-28 11:41 UTC, kof commented on apps/builder/app/builder/features/style-panel/style-layer-utils.ts
> +export const extractNameAndValueFromLayer = (
It would be great to have a few tests for it too

2024-06-28 11:42 UTC, kof commented on apps/builder/app/builder/features/style-panel/style-layer-utils.ts
> +  property: StyleProperty,
why not using a list of specific properties?

2024-06-28 11:42 UTC, kof commented on apps/builder/app/builder/features/style-panel/style-layer-utils.ts
> +  property: StyleProperty,
because right now you kinda claim to support them all from the interface and then throw an error if one passes you the wrong one

2024-06-28 11:43 UTC, kof requested changes
small changes needed

2024-07-01 17:02 UTC, JayaKrishnaNamburu commented
sure, will fix all the issue. Little caught up today.

2024-07-03 10:55 UTC, kof commented on apps/builder/app/builder/features/style-panel/style-layer-utils.test.ts
> +  "name": "Outer shadow:  3px 3px 10px",
Why is it "Outer shadow" vs "Drop Shadow" both both upper case? or "Inner shadow"

Which one should be used consistently?

2024-07-03 10:57 UTC, kof approved these changes
please fix inconsistent upper case usage

2024-07-03 11:52 UTC, merged