feat: Highlight navigator item when canvas instance is hovered
webstudio-is/webstudio pull request #3999
Opened 2024-08-22 19:50 UTC by kof

Closes https://github.com/webstudio-is/webstudio/issues/3757

## Description

When instance on canvas is hovered, we want to highlihgt the same instance in the navigator

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env` file

2024-08-22 20:41 UTC, johnsicili requested changes
Glitch when hovering over content embed

https://github.com/user-attachments/assets/810bca2d-90f7-44b2-a92f-4f1e8e2c9877

2024-08-22 21:05 UTC, kof commented
@johnsicili the glitch is there because between instances mouse hovers parent instance. Content embed has display contents, so it itself doesn't have a container that can be hovered I think. 

Its definitely a separate bug.

2024-08-22 21:23 UTC, kof commented
Might be actually impossible to fix ... display: contents doesn't have a layout and so there is no way to know mouse is hovering it

2024-08-23 08:52 UTC, TrySound approved these changes

2024-08-23 09:14 UTC, merged