experimental: generate root styles for published sites
webstudio-is/webstudio pull request #4177
Opened 2024-09-28 22:03 UTC by TrySound

Ref https://github.com/webstudio-is/webstudio/issues/3399

- render layout hack as root preset styles
- generate root user styles on published sites
- bumped a couple of deps

<img width="240" alt="Screenshot 2024-09-28 at 23 25 08" src="https://github.com/user-attachments/assets/eaf7476e-f488-4f1f-89db-6d464c05b35f">

2024-09-29 14:43 UTC, johnsicili requested changes
Preset root styles (at least grid and height) don't show in the Style Panel until clicking on the body/possibly any instance that has styles.

1. Refresh page
2. Check root styles see no grid
3. Click body
4. Click root see grid


https://github.com/user-attachments/assets/54f1ce64-75ba-4e89-8d02-ae577382f3c4

2024-09-29 15:10 UTC, TrySound commented
@johnsicili was a separate bug Ivan fixed, rebased. Now should work as expected.

2024-09-29 15:22 UTC, johnsicili approved these changes

2024-10-01 07:08 UTC, istarkov approved these changes

2024-10-01 10:54 UTC, merged