experimental: support css variables in dedicated sections
webstudio-is/webstudio pull request #4212
Opened 2024-10-03 22:55 UTC by TrySound

Ref https://github.com/webstudio-is/webstudio/issues/3399

Added support for entering and autocomplete of css variables to dedicated style sections like size and typography.

- color control
- text control

Also improved autocomplete to search with both var(--name) and --name.

![Screenshot 2024-10-04 at 01 51 12](https://github.com/user-attachments/assets/aca0f63d-8063-4676-877b-cc90e492ce9a)

2024-10-03 23:31 UTC, kof approved these changes

2024-10-04 00:16 UTC, johnsicili requested changes
OMG you're moving fast.

Looks good. Autocomplete is amazing! I searched `var--letter` and it still pulled up my letter spacing vars!

## Needs fixing
1. Border vars autocomplete not working (color, radius, width) though manual entry works. If this was not intended to be supported here let me know and I'll approve.

## Minor
1. Would be nice to have type checking so I can't use a color var in my font size field. I think browsers handle this well though so nbd.
2. I see this is for dedicated sections with color and text control so I guess it's known there is no support for things like transition duration and any of the layered css styles

2024-10-04 07:46 UTC, TrySound commented
Borders, easings, gradients will do separately. As for type checking, would leave it for after launch. Can be complicated.

2024-10-04 12:25 UTC, johnsicili approved these changes

2024-10-04 22:41 UTC, merged