feat: support paste styles in advanced section
webstudio-is/webstudio pull request #4323
Opened 2024-10-20 10:19 UTC by TrySound

Ref https://github.com/webstudio-is/webstudio/issues/3399 https://github.com/webstudio-is/webstudio/issues/3540

Here added two more features to advanced panel

1. When search for property, user can enter css declarations like `width: 100px; height: 200px;` and press enter instead of searching for property and editing property after creation.

2. When search for property, user can paste css declarations from some theme editor or figma, this is useful interop with other tools

Note: this does not support breakpoints, states or tokens. Declarations are inserted only within currently selected style source and state.

https://github.com/user-attachments/assets/1f37f5d1-11b9-4f05-ae4d-a7c647ae14b6

2024-10-20 10:30 UTC, kof commented
- [ ] we should probably update the placeholder in that input to better reflect this new capability. Maybe "Add CSS"?

2024-10-20 10:38 UTC, kof commented
- [ ] when I pasted, I didn't expect it to insert them all right away, I expected to see them in the input then hit enter. This beggs the question if input is the right element for this, I think what you want here is either code editor component or just auto growing textarea like we have in the settings

2024-10-20 10:40 UTC, kof requested changes
A few things with ux need improvement, otherwise works great! Great idea turning that input into effectively a paste editor

2024-10-20 12:34 UTC, TrySound commented
I wouldn't want to to be "css editor" caz advanced panel is already an editor itself. I see it more like a command line where user can write one-liners. Styles are applied with form on "Enter", multiline editor will kill this simplicity.

2024-10-20 13:25 UTC, kof commented
> user can write one-liners

yeah, though these are not one-liners, its more like the editor console

2024-10-20 13:30 UTC, TrySound commented
Terminal in editor? Drop history, it's one liner.

2024-10-20 13:34 UTC, kof commented
When you paste multiline css block it becomes multiline

2024-10-20 13:38 UTC, kof commented
Single line or multi line, its a detail though, yes, conceptually something like the cli, though we need to make pasted multiline block editable comfortably before sending

2024-10-20 13:52 UTC, TrySound commented
Sending where? User already copied what is needed. Why it needs to be edited? How user should apply multiline changes? Enter doesn't work anymore. Add "save" button?

2024-10-20 14:00 UTC, TrySound commented
It's actually similar to paste markdown. We do not prompt user with this markdown before applying.

2024-10-20 15:52 UTC, kof commented
After thinking. I think the mindset here should be primarily around a single-line usage. So when pasted multiline content, textarea would grow, allowing you to see and edit, but enter would submit, shift+enter would add a newline.

2024-10-21 08:47 UTC, TrySound commented
Downshift completely fails with textarea

2024-10-21 09:02 UTC, kof approved these changes

2024-10-21 09:07 UTC, merged