fix: relax detaching constraint
webstudio-is/webstudio pull request #4672
Opened 2024-12-29 13:07 UTC by TrySound

Every time somebody is facing invalid constraint issue whole tree is blocked from deleting instances except the problematic one with actual issue.

Here rewrote detachability check to validate only ancestors and avoid traversing potentially problematic siblings.

2024-12-29 13:39 UTC, kof approved these changes

2024-12-30 00:04 UTC, johnsicili requested changes
1. Add nav menu
2. Del menu content
3. See error 

https://github.com/user-attachments/assets/630a51e3-f825-40d2-948a-64833e4ce368

2. Also body in prod is "detachable" as it shows the dragging ability

2025-01-04 18:27 UTC, istarkov approved these changes

2025-01-04 18:28 UTC, TrySound commented
Fixed 1 and 2. And yes we replaced "detachable" flag with constraints so instead of draggability we check if instance can be dropped considering all constraints.

2025-01-06 19:28 UTC, merged